### ISSUE TITLE
`set!-transformer?` missing

### ISSUE THREAD

**Issue by vkirilichev** [pycket/pycket#153]
This primitive is needed to test `struct-info?`.

**Comment by samth** [comment]
This is a struct type property, so it should be handled like the others we've defined.

**Comment by vkirilichev** [comment]
@samth it should return true not only if an argument  is an instance of a structure type with this property, but also if it is a value created by make-set!-transformer.
This `assignment transformers` is a special object, that we don't have, isn't it?

**Comment by samth** [comment]
Right, in that sense it's sort of like `procedure?`. We don't currently have anything about transformers, since we don't implement macros, but this should be easy to add.

**Comment by vkirilichev** [comment]
ah, ok

**Comment by vkirilichev** [comment]
@samth can you explain me the description of `struct-info`? It is a bit confusing:
1. [A transparent structure type also allows reflective operations, such as struct? and struct-info, to be used on its instances](http://docs.racket-lang.org/guide/define-struct.html).
Transparent structure means that the current inspector is either #f of 'prefab, right? But:
2. [`struct-type` returns a structure type descriptor of the most specific type for which v is an instance, and for which the current inspector has control](http://docs.racket-lang.org/reference/inspectors.html?q=struct-info#%28def._%28%28quote._~23~25kernel%29._struct-info%29%29).
That means, it has to return #f always until the current inspector is not #f or 'prefab, but it returns a structure type in Racket.
