### ISSUE TITLE
build-list missing?

### ISSUE THREAD

**Issue by magnusmorton** [pycket/pycket#158]
build-list appears to be missing from pycket.

**Comment by krono** [comment]
[racket dock w/ test](http://docs.racket-lang.org/reference/pairs.html?q=build-list#%28def._%28%28lib._racket%2Fprivate%2Flist..rkt%29._build-list%29%29)

**Comment by sabauma** [comment]
This seems to be an issue with using `#lang pycket`, since we don't have `build-list` as  a primitive. It looks like `#lang racket/base` provides an implementation that works with Pycket, though.

**Comment by samth** [comment]
This isn't really a bug.
