### ISSUE TITLE
NaN tagging of fixnums breaks post translation

### ISSUE THREAD

**Issue by sabauma** [pycket/pycket#199]
Something fishy going on here
Here is a small test program which creates a singleton vector containing
a flonum and then writes the fixnum zero. The strategy correctly transitions to
use the tagged-flonum strategy.

```racket
#lang pycket

(define v (vector 0.0))
(display v)
(display "\n")

(vector-set! v 0 0)
(display v) (display "\n")
```

This example prints the correct result `#(0)` when interpreted, but produces
`#(nan)` post translation. The bit pattern of the floating-point value read from
the vector corresponds to the cannonical NaN rather than the one used to
represent the tagged fixnum. Investigation is ongoing.

**Comment by samth** [comment]
My guess would be that PyPy assumes that NaNs can be switched.

**Comment by krono** [comment]
at least `rfloat.py` from the rlib has only one `NAN` that is used throughout. It's not like they think it can be switched, rpython only ever returns one kind of NAN to any operation

So (some-op sabaumans_NaN anything) ; -> rpyhtons NAN

**Comment by sabauma** [comment]
It seems that the translator replaces the tagged floating point value with the following expression in the generated C code

```c
l_v416859 = (-(Py_HUGE_VAL/Py_HUGE_VAL));
goto block3;
```

`Py_HUGE_VAL` seems to be the constant defining floating point `+INF`. Oddly,
`+INF/+INF` seems to result `-NaN`.  Where `l_v416859` is the return value. This
is rather suspicious though, this code is generated from the following Python
code.

```python
if isinstance(w_val, W_Fixnum) and w_val.value == 0:
    return FIXNUM_ZERO_NAN
```

The constant `FIXNUM_ZERO_NAN` appears at other points in the code and is not
replaced by `-(Py_HUGE_VAL/Py_HUGE_VAL)` in those instances. I suspect
supporting more than just `0` would prevent whatever specialization is leading
to this odd bit of C code. This seems like a bug in the translator to me,
especially since `rpython.rlib.longlong2float` has utilities for doing this kind
of NaN tagging.

**Comment by krono** [comment]
@sabauma see https://bitbucket.org/pypy/pypy/src/4afa4a9d8caffdd737e4b8f24c157a939c9127d2/rpython/rlib/rfloat.py?at=default&fileviewer=file-view-default#rfloat.py-184

**Comment by sabauma** [comment]
I realize that there is a canonical NaN used by various RPython libraries (and pretty much all hardware), but the translator should not conflate NaNs with different bit patterns (and it certainly should not do so inconsistently).
