### ISSUE TITLE
Missing hash iteration functions

### ISSUE THREAD

**Issue by samth** [pycket/pycket#201]
Needed for the linklet branch of racket.

See all the immutable ops here:
`http://docs.racket-lang.org/reference/unsafe.html?q=unsafe-immutable#%28def._%28%28lib._racket%2Funsafe%2Fops..rkt%29._unsafe-immutable-hash-iterate-first%29%29

**Comment by sabauma** [comment]
63555ef should handle everything in that list except weak hash tables, which we do not currently have implemented anyway.
