### ISSUE TITLE
floating-point-bytes->real buggy on 32 bit architectures

### ISSUE THREAD

**Issue by PatrickMaier** [pycket/pycket#203]
floating-point-bytes->real works correctly on 64 bit architectures but not on 32 bit.

On 32bit platforms (floating-point-bytes->real (real->floating-point-bytes 12.34 8)) does not evaluate to 12.34 but to a completely different number such as 1.01855797962e-314.

The attached patch, or PR #204, should fix this.

[floating-point-bytes-to-real-32bit-patch.txt](https://github.com/pycket/pycket/files/1056496/floating-point-bytes-to-real-32bit-patch.txt)

**Comment by cfbolz** [comment]
Could you please paste the error?

**Comment by samth** [comment]
Can you turn the patch into a pull request?

**Comment by sabauma** [comment]
@PatrickMaier if you really depend on floating-point-bytes->real and its inverse, be sure to validate them for their use cases. They are currently are untested and do not have support for some of their arguments.

**Comment by PatrickMaier** [comment]
@samth I have submitted a pull request.

@sabauma I am aware that floating-point-bytes->real and its inverse only work for 64bit doubles. I don't intend to serialise single-precision floats. My code exercises serialisation fairly heavily and appears to work as intended, e.g. a Mandelbrot image still looks like a Mandelbrot image. I'm fairly confident that for doubles these functions work as they should.
