### ISSUE TITLE
string->number problems

### ISSUE THREAD

**Issue by samth** [pycket/pycket#219]
```
[samth@huor:~/.../racket-test-core/tests/racket (master) plt] pycket-c
Welcome to Pycket v6.90.0.28
> (string->number "0.0f0")
string->number: host `string->number` failed on 0.0f0
```

**Comment by samth** [comment]
Another issue: `2e45`

**Comment by samth** [comment]
`pycket-c --verbose 2 -l racket/contract/base` still fails with

```
string->number: host `string->number` failed on FeedFacf
```

**Comment by cderici** [comment]
I just noticed that, apparently `"f" in s` not a good predicate to recorgnize numbers like "0.0f0" :) Fix coming up

**Comment by samth** [comment]
The issue is in `compiler/private/mach-o.rkt`

**Comment by samth** [comment]
Another problem: `3.1415926535897932385t0`.

**Comment by cderici** [comment]
@samth What is the meaning of that `t`? I don't see it in the grammar in [(Reading Numbers)](https://docs.racket-lang.org/reference/reader.html?q=string-%3Enumber#%28part._parse-number%29) and it looks like more than just a double precision float.

**Comment by samth** [comment]
It's an extflonum, see https://docs.racket-lang.org/reference/extflonums.html?q=string-%3Enumber#%28tech._extflonum%29

**Comment by cderici** [comment]
Ah I see, ok, thanks
