### ISSUE TITLE
mark linklet fields as immutable

### ISSUE THREAD

**Issue by samth** [pycket/pycket#223]
Many of the fields of new data structures created recently (such as `W_LinkletInstance`) need to be marked as immutable so that rpython can optimize them.

**Comment by cfbolz** [comment]
Similarly, the LinkletVar class needs immutable fields declared. @samth told me that their ``.w_value`` field should change exactly once. If that's the case, it should be declared quasi-immutable, like this:

    _immutable_fields_ = ["w_value?", ...potential further fields...]

However, the code is a bit convoluted so I couldn't quite convince myself that ``.w_value`` really changes only once.

**Comment by cfbolz** [comment]
optimizing ``LinkletVar`` like this is quite important, about a third of all trace operations seem to be concerned with operating on ``LinkletVar``s
