### ISSUE TITLE
can't find module error for a module that exists - OLD P.

### ISSUE THREAD

**Issue by cderici** [pycket/pycket#231]
hash tests produce 2 errors both of which has the same message

(exn:fail can't find module /home/cderici/racketland/racket/racket/collects/racket/private/for.rkt for check-range #<continuation-mark-set>)

Can be reproduced by 

`pypy pypy/pytest.py pycket -k test_hash.py`

**Comment by samth** [comment]
Probably we can't use `#lang pycket` programs using `in-range` anymore -- `#lang pycket` is a hack anyway.

**Comment by samth** [comment]
Just add an explicit require of that file, which will increase testing time somewhat less.

**Comment by cderici** [comment]
Oh ok, that seems to work
