### ISSUE TITLE
loading a second linklet at boot

### ISSUE THREAD

**Issue by cderici** [pycket/pycket#252]
When I load another linklet besides the `expander.rktl.linklet` (in this case the `fasl.rktl.linklet`), I saw that the primitives that are exported from `fasl` linklet are not accessible in the repl, we keep getting "reference to **uninitialized** variable" error. So I manually wrote a small linklet json that defines and exports a function and load that one instead (alongside with the expander), and I was able to observe the same behavior.

Recall that when we run an expression in the REPL a linklet is created and compiled and instantiated over a particular target instance named the `toplevel`.

So I looked at what happens in 3 different cases: 1) using a func defined/exported by the expander, 2) using a func defined/exported by the second linklet, 3) using a kernel function, and I saw an interesting difference in the way they're compiled. Here's the input s-exp to `compile-linklet` for each of those cases:

\> (read (open-input-string 1))
> (linklet ((bunch-of-same-imp-ids) (read)) () (read (open-input-string 1)))

the `read` id is registered as an import.

\> (add5 3)
> (linklet ((bunch-of-same-imp-ids)) (add5) (add5 3))

the `add5` is written as an undefined export, where it's value is expected to be found in the target instance during the instantiation (note that it's the `toplevel` and does not have the `add5`).

\> (string? 3)
> (linklet ((bunch-of-same-imp-ids)) () (string? 3))'

`string?` is neither an import, nor an export, so it's gonna be a `ModuleVar` (by sexp->ast) which is expected.

We see a similar behavior without the repl too. When I try to run a file containing `(module a '#%kernel (add5 3))` the expansion fails (it never even gets to compile-linklet) with `exn:fail:syntax:unbound : add5: unbound identifier`. My guess is that the namespace in which we expand the module doesn't contain the id `add5`, which probably could explain the behavior in the REPL too.

**Comment by samth** [comment]
1. The goal of loading the fasl linklet isn't to use it at the repl (you know that, I think, but just being clear).
2. It is unsurprising that these bindings are not available to user programs. User programs see binding exposed by modules such as `'#%kernel`. Those modules are constructed explicitly by the expander, and are not just reflections of every value that is `@expose`d. This is, for example, why even though the value `@expose`d as `datum->syntax` produces a `W_Correlated`, that isn't what `datum->syntax` from `'#%kernel` does. 
3. Here's a function that gets an arbitrary exposed name:
```
(require '#%linklet)
(define-values (get-primitive)
  (lambda (sym)
    (define-values (s) (if (eq? sym 'f) 'g 'f))
    (define-values (l) (compile-linklet `(linklet () (,s) (define-values (,s) ,sym))))
    (define-values (li) (instantiate-linklet l null))
    (instance-variable-value li s)))
```
